"""ebanetting — vega netting under the EBA Prudent Valuation variance test.

Implements the technical note "Netting des sensibilités vega sous le test
de variance" (AVA MPU, Delegated Regulation (EU) 2016/101): the passage
of granular vega onto the test nodes (sandwich of passage matrices,
Theoreme 1), netting as an aggregation operator, the tracking-error
variance test, the conservatism floor, the two-node closed form
(Theoreme 2) and the greedy agglomerative optimiser with adverse
correlation stress.

Everything is computed with ordinary matrix products and sum reductions
on the (tenor, strike) grid — no Kronecker / tensor product is ever
assembled, even under the decoupled-correlation hypothesis (annex).
"""

from .datasource import (
    DataSource,
    JSONBundleSource,
    JSONScenarioSource,
    MarketDataBundle,
    MatrixScenarioSource,
    ScenarioSource,
    SyntheticDataSource,
    nearest_correlation,
)
from .model import KAPPA_90, UncertaintyModel
from .netting import NettingScheme, SchemeEvaluation, SetStat, two_bucket
from .optimizer import (
    GreedyResult,
    MergeStep,
    greedy_netting,
    robust_netting,
    stress_bundle,
)
from .passage import (
    PassageResult,
    offgrid_residual,
    passage_matrix,
    project,
    project_bundle,
    restrict_shocks,
    restriction_matrix,
)
from .clustering import (
    DecoupledResult,
    Dendrogram,
    base_risk_distance,
    build_dendrogram,
    cut_pivots,
    decoupled_netting,
    evaluate_cut,
    stability_report,
    stable_cut,
)
from .reporting import audit_json, build_audit_pack
from .scenario import (
    ScenarioReport,
    preset_labels,
    score_scenario,
    smile_decomposition,
)
from .twolayer import (
    GroupDecision,
    SmileModel,
    TrancheMerge,
    TwoLayerResult,
    barycenter_pivot,
    book_variance,
    cut_tranche,
    evaluate_book,
    fit_smile_model,
    generated_correlation,
    group_projections,
    group_residual_variance,
    majorant_residual_sd,
    model_distance,
    tranche_dendrogram,
)
from .engine import (
    EngineModel,
    EngineRun,
    adjusted_rand_index,
    cell_distances,
    cell_liquidity,
    cut_engine,
    engine_dendrogram,
    evaluate_book_engine,
    fit_engine_model,
    flip_flop,
    min_benefit_guard,
    orthonormal_basis,
    principal_angle_cosines,
    select_cut,
    simulate_panel,
    stale_cells,
    stress_engine_model,
    survival_frequencies,
    winsorize_panel,
)
from .mockdata import (
    MockEnvironment,
    generate_book_extracts,
    generate_surface_extract,
    load_mock_environment,
    parse_book_extracts,
    parse_surface_extract,
)
from .spectral import (
    SpectralDiagnostic,
    node_covariance,
    spectral_clean,
    spectral_diagnostic,
    subspace_stability,
)

__version__ = "2.5.0"

__all__ = [
    "PassageResult",
    "passage_matrix",
    "project",
    "project_bundle",
    "restriction_matrix",
    "restrict_shocks",
    "offgrid_residual",
    "DecoupledResult",
    "Dendrogram",
    "base_risk_distance",
    "build_dendrogram",
    "cut_pivots",
    "decoupled_netting",
    "evaluate_cut",
    "stability_report",
    "stable_cut",
    "DataSource",
    "JSONBundleSource",
    "JSONScenarioSource",
    "MarketDataBundle",
    "MatrixScenarioSource",
    "ScenarioSource",
    "SyntheticDataSource",
    "nearest_correlation",
    "KAPPA_90",
    "UncertaintyModel",
    "NettingScheme",
    "SchemeEvaluation",
    "SetStat",
    "two_bucket",
    "GreedyResult",
    "MergeStep",
    "greedy_netting",
    "robust_netting",
    "stress_bundle",
    "audit_json",
    "build_audit_pack",
    "ScenarioReport",
    "preset_labels",
    "score_scenario",
    "smile_decomposition",
    "SpectralDiagnostic",
    "node_covariance",
    "spectral_clean",
    "spectral_diagnostic",
    "subspace_stability",
    "GroupDecision",
    "SmileModel",
    "TrancheMerge",
    "TwoLayerResult",
    "barycenter_pivot",
    "book_variance",
    "cut_tranche",
    "evaluate_book",
    "fit_smile_model",
    "generated_correlation",
    "group_projections",
    "group_residual_variance",
    "majorant_residual_sd",
    "model_distance",
    "tranche_dendrogram",
    "EngineModel",
    "EngineRun",
    "adjusted_rand_index",
    "cell_distances",
    "cell_liquidity",
    "cut_engine",
    "engine_dendrogram",
    "evaluate_book_engine",
    "fit_engine_model",
    "flip_flop",
    "min_benefit_guard",
    "orthonormal_basis",
    "principal_angle_cosines",
    "select_cut",
    "simulate_panel",
    "stale_cells",
    "stress_engine_model",
    "survival_frequencies",
    "winsorize_panel",
    "MockEnvironment",
    "generate_book_extracts",
    "generate_surface_extract",
    "load_mock_environment",
    "parse_book_extracts",
    "parse_surface_extract",
]
