"""Scenario testing: score any user-defined netting scheme.

A scenario is an (M, K) integer label matrix over the (tenor, strike)
grid — supplied interactively, from a :class:`~ebanetting.datasource.ScenarioSource`,
or generated by the optimiser. The *variance score* is the R^2 of the
regression of DeltaPi on the netted proxy (Definition 3): the scenario
passes the EBA variance test iff R^2 >= alpha, and the conservatism
floor (eq. 7) iff AVA(P) >= kappa sqrt(Var(DeltaPi)).

Also implements a hierarchical smile decomposition (complementary): per
tenor, project the strike profile of vega on the local basis
{1, (k - k_ATM), (k - k_ATM)^2} to isolate level (nettable),
risk-reversal and butterfly exposures.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .datasource import MarketDataBundle
from .model import UncertaintyModel
from .netting import NettingScheme, SchemeEvaluation, Weighting

__all__ = ["ScenarioReport", "score_scenario", "preset_labels", "smile_decomposition"]


@dataclass(frozen=True)
class ScenarioReport:
    evaluation: SchemeEvaluation

    @property
    def variance_score(self) -> float:
        """R^2 of the netted proxy — the headline score of the scenario."""
        return self.evaluation.r2

    @property
    def verdict(self) -> str:
        ev = self.evaluation
        if ev.admissible:
            return "ADMISSIBLE"
        if not ev.passes_variance and not ev.passes_floor:
            return "REJECTED — variance test and floor"
        if not ev.passes_variance:
            return "REJECTED — variance test (R² < α)"
        return "REJECTED — conservatism floor (7)"


def score_scenario(
    bundle: MarketDataBundle,
    labels: np.ndarray,
    alpha: float,
    kappa: float,
    weighting: Weighting = "pivot",
) -> ScenarioReport:
    model = UncertaintyModel(bundle=bundle, kappa=kappa)
    scheme = NettingScheme.from_labels(np.asarray(labels, dtype=int), weighting)
    return ScenarioReport(evaluation=scheme.evaluate(model, alpha))


def preset_labels(name: str, M: int, K: int) -> np.ndarray:
    """Standard candidate partitions used as scenario starting points."""
    if name == "singletons":
        return np.arange(M * K).reshape(M, K)
    if name == "per_tenor":      # collapse the smile, one set per maturity line
        return np.repeat(np.arange(M)[:, None], K, axis=1)
    if name == "per_strike":     # one set per strike column
        return np.repeat(np.arange(K)[None, :], M, axis=0)
    if name == "global":         # a single netting set
        return np.zeros((M, K), dtype=int)
    if name == "quadrants":      # short/long maturities x low/high strikes
        labels = np.zeros((M, K), dtype=int)
        labels[: M // 2, : K // 2] = 0
        labels[: M // 2, K // 2 :] = 1
        labels[M // 2 :, : K // 2] = 2
        labels[M // 2 :, K // 2 :] = 3
        return labels
    raise ValueError(f"unknown preset '{name}'")


def smile_decomposition(bundle: MarketDataBundle) -> list[dict]:
    """Stage-1 hierarchical netting diagnostic (complementary).

    Per tenor m, decompose the vega strike-profile on the local basis
    {1, x, x^2} with x = k - k_ATM (here moneyness offset K/F - 1):
    the level component is nettable, the risk-reversal and butterfly
    residuals carry their own (wider) consensus uncertainty and are the
    reason per-tranche variance tests fail.
    """
    x = np.asarray(bundle.strikes) - 1.0
    out = []
    for m in range(bundle.M):
        row = bundle.vega[m]
        level = float(row.sum())
        rr = float(row @ x)
        fly = float(row @ x ** 2)
        # Variance of the tranche residual after collapsing to the level
        # with the ATM-pivot shock: nu_resid' Sigma_m nu_resid where the
        # level part is explained by the pivot.
        s_m = bundle.s[m]
        rho_k = bundle.corr_strike if bundle.corr_strike is not None else np.eye(bundle.K)
        d_m = np.diag(s_m)
        sigma_m = d_m @ rho_k @ d_m              # D rho D — usual matrix products
        pivot = int(np.argmin(np.abs(x)))
        e = row.copy()
        e[pivot] -= level  # residual exposure if the whole line nets on ATM
        te2_line = float(e @ sigma_m @ e)
        var_line = float(row @ sigma_m @ row)
        out.append(
            {
                "tenor": bundle.tenors[m],
                "level": level,
                "risk_reversal": rr,
                "butterfly": fly,
                "te2_line": te2_line,
                "var_line": var_line,
                "r2_line": 1.0 - te2_line / var_line if var_line > 0 else 1.0,
            }
        )
    return out
